export const KITTU_PRACTICE_MODES = ["NCERT-based", "Exam-pattern", "High-yield"] as const;
export type KittuPracticeMode = (typeof KITTU_PRACTICE_MODES)[number];

export const KITTU_EXAM_TRACKS = [
  "All Exams",
  "NEET",
  "JEE Main",
  "JEE Advanced",
  "CBSE MCQ",
  "CBSE Class 9-10",
  "CBSE Class 11-12 Science",
  "CBSE Class 11-12 Commerce",
  "ICSE MCQ",
  "ICSE Class 9-10",
  "ISC Science",
  "ISC Commerce",
  "State Board MCQ",
  "UPSC/SSC/Bank",
  "CA Foundation",
  "CA Intermediate",
  "CUET",
  "CLAT/Law",
  "NDA/CDS",
  "UPSC CSE",
  "SSC",
  "Banking",
  "Railway",
  "Punjab ETT Cadre",
  "PSTET/CTET",
  "PPSC Punjab",
  "Punjab PCS",
  "PSSSB",
  "Punjab Patwari",
  "Punjab Police",
  "Punjab Master Cadre",
  "Punjab Lecturer Cadre",
  "Punjab Clerk",
  "PSEB Class 9-10",
  "State PSC",
  "State Police",
  "State Teacher/TET",
  "State Patwari/Revenue",
  "State Clerk",
  "Other Competitive Exam",
] as const;

export type KittuPracticeBatch = {
  id: string;
  label: string;
  exam: string;
  subject: string;
  topic: string;
  mode: KittuPracticeMode;
  enabled: boolean;
};

export const KITTU_SUBJECT_TOPICS = {
  /* ---- Mega exam bank subjects (Bank, Railway, SSC, NEET, JEE, CA) ---- */
  Accounting: [
    "Accounting Principles",
    "Classification of Accounts",
    "Depreciation",
    "Journal Entries",
    "Ratio Analysis",
  ],
  "Banking Awareness": [
    "Banking Abbreviations",
    "Banking History",
    "Banking Numericals",
    "Banking Terms",
  ],
  Biology: [
    "Biological Classification",
    "Biomolecules",
    "Biotechnology",
    "Body Fluids and Circulation",
    "Breathing and Exchange of Gases",
    "Cell Cycle and Cell Division",
    "Cell Structure and Function",
    "Chemical Coordination",
    "Digestion and Absorption",
    "Ecology and Environment",
    "Excretory Products and Elimination",
    "Genetics and Evolution",
    "Human Health and Disease",
    "Human Physiology",
    "Molecular Basis of Inheritance",
    "Morphology of Flowering Plants",
    "Neural Control and Coordination",
    "Photosynthesis",
    "Plant Physiology",
    "Reproduction",
    "Respiration in Plants",
  ],
  "Business Economics": ["Elasticity of Demand", "Microeconomics"],
  "Business Law": [
    "Companies Act 2013",
    "Indian Contract Act 1872",
    "Legal Terms",
    "Negotiable Instruments Act 1881",
    "Partnership Act 1932",
  ],
  Chemistry: [
    "Acids Bases and Salts",
    "Chemical Formulae",
    "IUPAC Nomenclature",
    "Metallurgy",
    "Mole Concept",
    "Nuclear Chemistry",
    "Organic Chemistry Basics",
    "Periodic Classification",
    "Periodic Table",
    "Solutions",
    "Some Basic Concepts of Chemistry",
    "States of Matter",
  ],
  "Computer Awareness": [
    "Computer Abbreviations",
    "Computer Fundamentals",
    "Computer Generations",
    "File Formats",
    "Input and Output Devices",
    "Keyboard Shortcuts",
    "Memory Units",
  ],
  "Cost Accounting": ["Marginal Costing", "Material Costing"],
  "English Language": [
    "Antonyms",
    "Idioms and Phrases",
    "One Word Substitution",
    "Prepositions",
    "Spellings",
    "Subject Verb Agreement",
    "Synonyms",
  ],
  "General Awareness": [
    "Art and Culture",
    "Government Schemes",
    "Indian Geography",
    "Indian History",
    "Indian Polity",
    "Punjab GK",
    "Science and Technology",
    "Sports",
    "Static GK",
    "World Geography",
  ],
  Mathematics: [
    "Binomial Theorem",
    "Circles",
    "Differentiation",
    "Integration",
    "Logarithms",
    "Matrices and Determinants",
    "Quadratic Equations",
    "Sequences and Series",
    "Straight Lines",
  ],
  Physics: [
    "Current Electricity",
    "Laws and Principles",
    "Laws of Motion",
    "Motion in a Straight Line",
    "Ray Optics",
    "Waves",
    "Work Energy and Power",
  ],
  "Quantitative Aptitude": [
    "Average",
    "Boats and Streams",
    "Compound Interest",
    "Discount",
    "Mensuration",
    "Mixture and Alligation",
    "Number System",
    "Partnership",
    "Percentage",
    "Permutation and Combination",
    "Pipes and Cisterns",
    "Probability",
    "Problems on Ages",
    "Problems on Trains",
    "Profit and Loss",
    "Ratio and Proportion",
    "Simple Interest",
    "Simplification",
    "Time and Work",
    "Time, Speed and Distance",
  ],
  Taxation: ["GST Computation", "Goods and Services Tax"],
  /* ---- Existing KKCC subjects ---- */
  Polity: [
    "Constitution Basics",
    "Fundamental Rights",
    "Directive Principles",
    "Parliament",
    "President and Governor",
    "Panchayati Raj",
    "Judiciary",
    "Local Government",
  ],
  "English Grammar": [
    "Tenses",
    "Subject-Verb Agreement",
    "Articles and Determiners",
    "Prepositions",
    "Voice",
    "Narration",
    "Error Spotting",
    "Reading Comprehension",
  ],
  "Hindi Grammar": [
    "संग्या और सर्वनाम",
    "क्रिया और काल",
    "संधि और समास",
    "कारक और विभक्ति",
    "पर्यायवाची और विलोम शब्द",
    "मुहावरे और लोकोक्तियाँ",
    "वाक्य शुद्धि",
  ],
  Math: [
    "Number System",
    "Simplification",
    "Percentage",
    "Ratio and Proportion",
    "Profit and Loss",
    "Simple Interest",
    "Time and Work",
    "Data Interpretation",
  ],
  "Math Class 9": [
    "Number Systems",
    "Polynomials",
    "Coordinate Geometry",
    "Linear Equations in Two Variables",
    "Lines and Angles",
    "Triangles",
    "Quadrilaterals",
    "Circles",
    "Heron's Formula",
    "Statistics",
  ],
  "Math Class 10": [
    "Real Numbers",
    "Polynomials",
    "Pair of Linear Equations",
    "Quadratic Equations",
    "Arithmetic Progressions",
    "Triangles",
    "Coordinate Geometry",
    "Trigonometry",
    "Circles",
    "Surface Areas and Volumes",
    "Statistics",
    "Probability",
  ],
  Science: [
    "Physics Basics",
    "Mechanics",
    "Work and Energy",
    "Optics",
    "Current Electricity",
    "Chemistry Basics",
    "Mole Concept",
    "Periodic Table",
    "Chemical Bonding",
    "Biology Basics",
    "Genetics",
    "Human Physiology",
    "Ecology",
    "Units and Measurements",
  ],
  "Science Class 9": [
    "Matter in Our Surroundings",
    "Is Matter Around Us Pure",
    "Atoms and Molecules",
    "Structure of the Atom",
    "The Fundamental Unit of Life",
    "Tissues",
    "Motion",
    "Force and Laws of Motion",
    "Gravitation",
    "Work and Energy",
    "Sound",
    "Natural Resources",
  ],
  "Science Class 10": [
    "Chemical Reactions and Equations",
    "Acids, Bases and Salts",
    "Metals and Non-metals",
    "Carbon and Its Compounds",
    "Life Processes",
    "Control and Coordination",
    "How Do Organisms Reproduce",
    "Heredity",
    "Light Reflection and Refraction",
    "Human Eye and Colourful World",
    "Electricity",
    "Magnetic Effects of Electric Current",
    "Our Environment",
  ],
  SST: [
    "History",
    "Geography",
    "Civics",
    "Economics",
    "Nationalism in India",
    "Resources and Development",
    "Democracy and Diversity",
    "Money and Credit",
  ],
  "Punjab History": [
    "Sikh Gurus",
    "Maharaja Ranjit Singh",
    "Anglo-Sikh Wars",
    "Freedom Movement in Punjab",
    "Ghadar Movement",
    "Punjab Reorganisation",
  ],
  "Punjab GK": [
    "Districts and Headquarters",
    "Rivers and Canals",
    "Folk Dances and Fairs",
    "Sports and Awards",
    "Important Places",
    "Current Static GK",
  ],
  "Punjab Geography": [
    "Malwa Majha Doaba Regions",
    "Rivers of Punjab",
    "Canal Irrigation",
    "Soils and Crops",
    "Climate",
    "Borders and Neighbouring States",
  ],
  "Punjab Economics": [
    "Agriculture",
    "Green Revolution",
    "Industry and MSME",
    "Budget Basics",
    "Employment",
    "Cooperative Sector",
  ],
  "Punjabi Paper A": ["ਪਠਨ ਬੋਧ", "ਪੱਤਰ ਲਿਖਣ", "ਸੰਖੇਪ ਲਿਖਣ", "ਅਨੁਵਾਦ", "ਸ਼ਬਦਾਵਲੀ", "ਸਰਕਾਰੀ ਭਾਸ਼ਾ"],
  "Punjabi Paper B": [
    "ਪੰਜਾਬੀ ਸਾਹਿਤ ਦਾ ਇਤਿਹਾਸ",
    "ਗੁਰਮਤਿ ਕਾਵਿ",
    "ਸੂਫ਼ੀ ਕਾਵਿ",
    "ਕਿੱਸਾ ਕਾਵਿ",
    "ਪੰਜਾਬੀ ਨਾਵਲ",
    "ਪੰਜਾਬੀ ਕਹਾਣੀ",
    "ਪੰਜਾਬੀ ਨਾਟਕ",
    "ਭਾਸ਼ਾ ਵਿਗਿਆਨ",
  ],
  "Punjabi Grammar": [
    "ਨਾਵ ਅਤੇ ਪੜਨਾਵ",
    "ਲਿੰਗ ਅਤੇ ਵਚਨ",
    "ਕਿਰਿਆ ਦੇ ਰੂਪ",
    "ਵਾਕ ਸੁਧਾਰ",
    "ਮੁਹਾਵਰੇ",
    "ਸਮਾਨਾਰਥੀ ਅਤੇ ਵਿਰੋਧੀ ਸ਼ਬਦ",
  ],
  "Punjabi Literature": [
    "ਕਵਿਤਾ",
    "ਗਦ",
    "ਲੇਖਕ ਅਤੇ ਰਚਨਾਵਾਂ",
    "ਵਿਸ਼ੇ",
    "ਸਾਹਿਤਕ ਅਲੰਕਾਰ",
    "ਸਾਹਿਤ ਵਿੱਚ ਪੰਜਾਬੀ ਸੱਭਿਆਚਾਰ",
  ],
  Commerce: [
    "Accounting Equation",
    "Journal Entries",
    "Business Law",
    "Economics Demand Supply",
    "Business Mathematics",
    "Partnership Basics",
  ],
  Law: ["Constitutional Law", "Legal Reasoning", "Torts", "Contracts", "Criminal Law Basics"],
  Reasoning: [
    "Analogy",
    "Series",
    "Coding-Decoding",
    "Syllogism",
    "Direction Sense",
    "Blood Relation",
    "Seating Arrangement",
    "Alphabet Test",
    "Clock and Calendar",
    "Coding and Decoding",
    "Mathematical Operations",
    "Number Series",
    "Ranking and Order",
  ],
  "Teaching Aptitude": [
    "Child Development",
    "Learning Theories",
    "Inclusive Education",
    "Assessment",
    "Pedagogy",
    "Classroom Management",
  ],
} as Record<string, string[]>;
export const KITTU_SUBJECT_OPTIONS = Object.keys(KITTU_SUBJECT_TOPICS);
