/**
 * General Awareness fact tables — static GK that repeats every year in
 * Bank, Railway, SSC, State PSC and Police exams.
 *
 * Each table feeds the fact-template engine, which builds forward and reverse
 * MCQs with distractors drawn from the same category.
 */

import {
  type FactRow,
  type Template,
  factTemplate,
  matchTemplate,
  statementTemplate,
  statementCountTemplate,
} from "./core";

const GA = [
  "Banking",
  "SSC",
  "Railway",
  "UPSC/SSC/Bank",
  "Punjab Police",
  "State Police",
  "CUET",
  "UPSC CSE",
  "State PSC",
  "PPSC Punjab",
  "Punjab Patwari",
  "Punjab Clerk",
  "State Clerk",
  "Punjab ETT Cadre",
  "Punjab Master Cadre",
  "PSTET/CTET",
  "State Teacher/TET",
  "NDA/CDS",
  "Punjab PCS",
  "PSSSB",
  "Punjab Lecturer Cadre",
  "PSEB Class 9-10",
  "SSC CGL",
  "SSC CHSL",
  "SSC MTS",
  "SSC GD Constable",
  "RRB NTPC",
  "RRB Group D",
  "RRB ALP",
  "CAPF",
];
const templates: Template[] = [];

function add(
  id: string,
  topic: string,
  difficulty: "Easy" | "Moderate" | "Difficult",
  rows: FactRow[],
  forward: string,
  reverse: string | undefined,
  explain: string,
  subject = "General Awareness",
) {
  templates.push(
    ...factTemplate({ id, subject, topic, difficulty, exams: GA, rows, forward, reverse, explain }),
    matchTemplate({ id, subject, topic, difficulty, exams: GA, rows }),
    statementTemplate({ id, subject, topic, difficulty, exams: GA, rows }),
    statementCountTemplate({ id, subject, topic, difficulty, exams: GA, rows }),
  );
}

/* ------------------------------------------------------- world capitals */

add(
  "gk:capital",
  "World Geography",
  "Easy",
  [
    { key: "Japan", value: "Tokyo" },
    { key: "France", value: "Paris" },
    { key: "Italy", value: "Rome" },
    { key: "Spain", value: "Madrid" },
    { key: "Portugal", value: "Lisbon" },
    { key: "Germany", value: "Berlin" },
    { key: "Austria", value: "Vienna" },
    { key: "Greece", value: "Athens" },
    { key: "Russia", value: "Moscow" },
    { key: "China", value: "Beijing" },
    { key: "South Korea", value: "Seoul" },
    { key: "North Korea", value: "Pyongyang" },
    { key: "Thailand", value: "Bangkok" },
    { key: "Vietnam", value: "Hanoi" },
    { key: "Indonesia", value: "Jakarta" },
    { key: "Malaysia", value: "Kuala Lumpur" },
    { key: "Philippines", value: "Manila" },
    { key: "Nepal", value: "Kathmandu" },
    { key: "Bhutan", value: "Thimphu" },
    { key: "Bangladesh", value: "Dhaka" },
    { key: "Sri Lanka", value: "Sri Jayawardenepura Kotte" },
    { key: "Pakistan", value: "Islamabad" },
    { key: "Afghanistan", value: "Kabul" },
    { key: "Iran", value: "Tehran" },
    { key: "Iraq", value: "Baghdad" },
    { key: "Turkey", value: "Ankara" },
    { key: "Saudi Arabia", value: "Riyadh" },
    { key: "United Arab Emirates", value: "Abu Dhabi" },
    { key: "Qatar", value: "Doha" },
    { key: "Israel", value: "Jerusalem" },
    { key: "Egypt", value: "Cairo" },
    { key: "Kenya", value: "Nairobi" },
    { key: "Nigeria", value: "Abuja" },
    { key: "South Africa", value: "Pretoria" },
    { key: "Morocco", value: "Rabat" },
    { key: "Ethiopia", value: "Addis Ababa" },
    { key: "Canada", value: "Ottawa" },
    { key: "United States of America", value: "Washington D.C." },
    { key: "Mexico", value: "Mexico City" },
    { key: "Brazil", value: "Brasilia" },
    { key: "Argentina", value: "Buenos Aires" },
    { key: "Chile", value: "Santiago" },
    { key: "Peru", value: "Lima" },
    { key: "Colombia", value: "Bogota" },
    { key: "Australia", value: "Canberra" },
    { key: "New Zealand", value: "Wellington" },
    { key: "Norway", value: "Oslo" },
    { key: "Sweden", value: "Stockholm" },
    { key: "Denmark", value: "Copenhagen" },
    { key: "Finland", value: "Helsinki" },
    { key: "Netherlands", value: "Amsterdam" },
    { key: "Belgium", value: "Brussels" },
    { key: "Switzerland", value: "Bern" },
    { key: "Poland", value: "Warsaw" },
    { key: "Ukraine", value: "Kyiv" },
    { key: "Myanmar", value: "Naypyidaw" },
    { key: "Maldives", value: "Male" },
    { key: "Mongolia", value: "Ulaanbaatar" },
  ],
  "What is the capital of %s?",
  "%s is the capital city of which country?",
  "The capital of %k is %v.",
);

/* ----------------------------------------------------------- currencies */

add(
  "gk:currency",
  "World Geography",
  "Easy",
  [
    { key: "Japan", value: "Yen" },
    { key: "China", value: "Yuan" },
    { key: "United Kingdom", value: "Pound Sterling" },
    { key: "United States of America", value: "US Dollar" },
    { key: "Russia", value: "Rouble" },
    { key: "South Korea", value: "Won" },
    { key: "Thailand", value: "Baht" },
    { key: "Vietnam", value: "Dong" },
    { key: "Indonesia", value: "Rupiah" },
    { key: "Malaysia", value: "Ringgit" },
    { key: "Bangladesh", value: "Taka" },
    { key: "Myanmar", value: "Kyat" },
    { key: "Iran", value: "Rial" },
    { key: "Saudi Arabia", value: "Riyal" },
    { key: "Israel", value: "Shekel" },
    { key: "Turkey", value: "Lira" },
    { key: "South Africa", value: "Rand" },
    { key: "Nigeria", value: "Naira" },
    { key: "Kenya", value: "Kenyan Shilling" },
    { key: "Egypt", value: "Egyptian Pound" },
    { key: "Brazil", value: "Real" },
    { key: "Mexico", value: "Peso" },
    { key: "Poland", value: "Zloty" },
    { key: "Sweden", value: "Krona" },
    { key: "Denmark", value: "Danish Krone" },
    { key: "Switzerland", value: "Swiss Franc" },
    { key: "Bhutan", value: "Ngultrum" },
    { key: "Mongolia", value: "Tugrik" },
    { key: "Kuwait", value: "Kuwaiti Dinar" },
    { key: "Afghanistan", value: "Afghani" },
  ],
  "What is the currency of %s?",
  "The %s is the official currency of which country?",
  "The currency of %k is the %v.",
);

/* ------------------------------------------------------- Indian capitals */

add(
  "gk:state-capital",
  "Indian Geography",
  "Easy",
  [
    { key: "Punjab", value: "Chandigarh" },
    { key: "Haryana", value: "Chandigarh" },
    { key: "Rajasthan", value: "Jaipur" },
    { key: "Gujarat", value: "Gandhinagar" },
    { key: "Maharashtra", value: "Mumbai" },
    { key: "Goa", value: "Panaji" },
    { key: "Karnataka", value: "Bengaluru" },
    { key: "Kerala", value: "Thiruvananthapuram" },
    { key: "Tamil Nadu", value: "Chennai" },
    { key: "Andhra Pradesh", value: "Amaravati" },
    { key: "Telangana", value: "Hyderabad" },
    { key: "Odisha", value: "Bhubaneswar" },
    { key: "West Bengal", value: "Kolkata" },
    { key: "Bihar", value: "Patna" },
    { key: "Jharkhand", value: "Ranchi" },
    { key: "Chhattisgarh", value: "Raipur" },
    { key: "Madhya Pradesh", value: "Bhopal" },
    { key: "Uttar Pradesh", value: "Lucknow" },
    { key: "Uttarakhand", value: "Dehradun" },
    { key: "Himachal Pradesh", value: "Shimla" },
    { key: "Assam", value: "Dispur" },
    { key: "Arunachal Pradesh", value: "Itanagar" },
    { key: "Nagaland", value: "Kohima" },
    { key: "Manipur", value: "Imphal" },
    { key: "Mizoram", value: "Aizawl" },
    { key: "Tripura", value: "Agartala" },
    { key: "Meghalaya", value: "Shillong" },
    { key: "Sikkim", value: "Gangtok" },
  ],
  "What is the capital of the Indian state of %s?",
  "%s is the capital of which Indian state?",
  "The capital of %k is %v.",
);

/* ---------------------------------------------------------- dance forms */

add(
  "gk:dance",
  "Art and Culture",
  "Moderate",
  [
    { key: "Bharatanatyam", value: "Tamil Nadu" },
    { key: "Kathakali", value: "Kerala" },
    { key: "Mohiniyattam", value: "Kerala" },
    { key: "Kuchipudi", value: "Andhra Pradesh" },
    { key: "Odissi", value: "Odisha" },
    { key: "Manipuri", value: "Manipur" },
    { key: "Sattriya", value: "Assam" },
    { key: "Kathak", value: "Uttar Pradesh" },
    { key: "Bhangra", value: "Punjab" },
    { key: "Giddha", value: "Punjab" },
    { key: "Garba", value: "Gujarat" },
    { key: "Lavani", value: "Maharashtra" },
    { key: "Bihu", value: "Assam" },
    { key: "Chhau", value: "Jharkhand" },
    { key: "Ghoomar", value: "Rajasthan" },
    { key: "Yakshagana", value: "Karnataka" },
    { key: "Nati", value: "Himachal Pradesh" },
    { key: "Cheraw", value: "Mizoram" },
  ],
  "The classical or folk dance %s belongs to which Indian state?",
  undefined,
  "%k is a well known dance form of %v.",
);

/* -------------------------------------------------------------- vitamins */

add(
  "gk:vitamin",
  "Science and Technology",
  "Easy",
  [
    { key: "Vitamin A", value: "Night blindness" },
    { key: "Vitamin B1", value: "Beri-beri" },
    { key: "Vitamin B3", value: "Pellagra" },
    { key: "Vitamin B12", value: "Pernicious anaemia" },
    { key: "Vitamin C", value: "Scurvy" },
    { key: "Vitamin D", value: "Rickets" },
    { key: "Vitamin K", value: "Delayed blood clotting" },
    { key: "Iodine", value: "Goitre" },
    { key: "Iron", value: "Anaemia" },
    { key: "Protein", value: "Kwashiorkor" },
  ],
  "Deficiency of %s causes which disease or disorder?",
  "%s is caused by the deficiency of which nutrient?",
  "A deficiency of %k causes %v.",
);

add(
  "gk:vitamin-name",
  "Science and Technology",
  "Moderate",
  [
    { key: "Vitamin A", value: "Retinol" },
    { key: "Vitamin B1", value: "Thiamine" },
    { key: "Vitamin B2", value: "Riboflavin" },
    { key: "Vitamin B3", value: "Niacin" },
    { key: "Vitamin B6", value: "Pyridoxine" },
    { key: "Vitamin B9", value: "Folic acid" },
    { key: "Vitamin B12", value: "Cyanocobalamin" },
    { key: "Vitamin C", value: "Ascorbic acid" },
    { key: "Vitamin D", value: "Calciferol" },
    { key: "Vitamin E", value: "Tocopherol" },
    { key: "Vitamin K", value: "Phylloquinone" },
  ],
  "What is the chemical name of %s?",
  "%s is the chemical name of which vitamin?",
  "The chemical name of %k is %v.",
);

/* --------------------------------------------------------- headquarters */

add(
  "gk:hq",
  "Static GK",
  "Moderate",
  [
    { key: "United Nations Organisation", value: "New York, USA" },
    { key: "World Health Organization", value: "Geneva, Switzerland" },
    { key: "International Monetary Fund", value: "Washington D.C., USA" },
    { key: "World Bank", value: "Washington D.C., USA" },
    { key: "World Trade Organization", value: "Geneva, Switzerland" },
    { key: "UNESCO", value: "Paris, France" },
    { key: "UNICEF", value: "New York, USA" },
    { key: "International Labour Organization", value: "Geneva, Switzerland" },
    { key: "International Court of Justice", value: "The Hague, Netherlands" },
    { key: "OPEC", value: "Vienna, Austria" },
    { key: "SAARC", value: "Kathmandu, Nepal" },
    { key: "ASEAN", value: "Jakarta, Indonesia" },
    { key: "Interpol", value: "Lyon, France" },
    { key: "Amnesty International", value: "London, United Kingdom" },
    { key: "International Olympic Committee", value: "Lausanne, Switzerland" },
    { key: "Asian Development Bank", value: "Manila, Philippines" },
    { key: "Reserve Bank of India", value: "Mumbai, India" },
    { key: "State Bank of India", value: "Mumbai, India" },
    { key: "Securities and Exchange Board of India", value: "Mumbai, India" },
    { key: "NABARD", value: "Mumbai, India" },
    { key: "Indian Space Research Organisation", value: "Bengaluru, India" },
    { key: "Defence Research and Development Organisation", value: "New Delhi, India" },
    { key: "Indian Council of Agricultural Research", value: "New Delhi, India" },
    { key: "Council of Scientific and Industrial Research", value: "New Delhi, India" },
  ],
  "Where is the headquarters of the %s located?",
  "Which organisation has its headquarters at %s?",
  "The headquarters of %k is at %v.",
);

/* ------------------------------------------------------------ first-in-India */

add(
  "gk:first-india",
  "Static GK",
  "Moderate",
  [
    { key: "first President of India", value: "Dr. Rajendra Prasad" },
    { key: "first Prime Minister of India", value: "Jawaharlal Nehru" },
    { key: "first woman Prime Minister of India", value: "Indira Gandhi" },
    { key: "first woman President of India", value: "Pratibha Patil" },
    { key: "first Vice President of India", value: "Dr. S. Radhakrishnan" },
    { key: "first Chief Justice of India", value: "Justice H. J. Kania" },
    { key: "first Indian to win a Nobel Prize", value: "Rabindranath Tagore" },
    { key: "first Indian in space", value: "Rakesh Sharma" },
    { key: "first woman of Indian origin in space", value: "Kalpana Chawla" },
    { key: "first Field Marshal of India", value: "Sam Manekshaw" },
    { key: "first Education Minister of India", value: "Maulana Abul Kalam Azad" },
    { key: "first Home Minister of India", value: "Sardar Vallabhbhai Patel" },
    { key: "first Speaker of the Lok Sabha", value: "G. V. Mavalankar" },
    { key: "first Governor General of independent India", value: "Lord Mountbatten" },
    { key: "first Indian Governor General of India", value: "C. Rajagopalachari" },
    { key: "first Indian woman to win an Olympic medal", value: "Karnam Malleswari" },
    { key: "first Election Commissioner of India", value: "Sukumar Sen" },
  ],
  "Who was the %s?",
  undefined,
  "The %k was %v.",
);

/* ------------------------------------------------------- important days */

add(
  "gk:days",
  "Static GK",
  "Easy",
  [
    { key: "Republic Day of India", value: "26 January" },
    { key: "Independence Day of India", value: "15 August" },
    { key: "Gandhi Jayanti", value: "2 October" },
    { key: "World Environment Day", value: "5 June" },
    { key: "International Yoga Day", value: "21 June" },
    { key: "World Health Day", value: "7 April" },
    { key: "World Water Day", value: "22 March" },
    { key: "International Women's Day", value: "8 March" },
    { key: "World Literacy Day", value: "8 September" },
    { key: "Teachers' Day in India", value: "5 September" },
    { key: "Children's Day in India", value: "14 November" },
    { key: "National Science Day in India", value: "28 February" },
    { key: "World Earth Day", value: "22 April" },
    { key: "Human Rights Day", value: "10 December" },
    { key: "World AIDS Day", value: "1 December" },
    { key: "National Youth Day in India", value: "12 January" },
    { key: "Constitution Day of India", value: "26 November" },
    { key: "World Population Day", value: "11 July" },
  ],
  "On which date is %s observed?",
  "Which important day is observed on %s?",
  "%k is observed on %v.",
);

/* ------------------------------------------------------------- articles */

add(
  "gk:article",
  "Indian Polity",
  "Difficult",
  [
    { key: "Article 14", value: "Equality before law" },
    { key: "Article 19", value: "Six freedoms including freedom of speech" },
    { key: "Article 21", value: "Protection of life and personal liberty" },
    { key: "Article 21A", value: "Right to free and compulsory education" },
    { key: "Article 32", value: "Right to constitutional remedies" },
    { key: "Article 44", value: "Uniform Civil Code" },
    { key: "Article 51A", value: "Fundamental Duties" },
    { key: "Article 72", value: "Pardoning power of the President" },
    { key: "Article 76", value: "Attorney General of India" },
    { key: "Article 110", value: "Definition of a Money Bill" },
    { key: "Article 123", value: "Ordinance making power of the President" },
    { key: "Article 143", value: "Advisory jurisdiction of the Supreme Court" },
    { key: "Article 148", value: "Comptroller and Auditor General of India" },
    { key: "Article 280", value: "Finance Commission" },
    { key: "Article 324", value: "Election Commission of India" },
    { key: "Article 352", value: "National Emergency" },
    { key: "Article 356", value: "President's Rule in a state" },
    { key: "Article 360", value: "Financial Emergency" },
    { key: "Article 368", value: "Amendment of the Constitution" },
  ],
  "Which provision of the Indian Constitution is dealt with by %s?",
  "Which Article of the Indian Constitution deals with %s?",
  "%k of the Indian Constitution deals with %v.",
  "General Awareness",
);

/* ------------------------------------------------------------- SI units */

add(
  "gk:si-unit",
  "Science and Technology",
  "Easy",
  [
    { key: "Force", value: "Newton" },
    { key: "Work or Energy", value: "Joule" },
    { key: "Power", value: "Watt" },
    { key: "Pressure", value: "Pascal" },
    { key: "Frequency", value: "Hertz" },
    { key: "Electric charge", value: "Coulomb" },
    { key: "Electric current", value: "Ampere" },
    { key: "Potential difference", value: "Volt" },
    { key: "Electrical resistance", value: "Ohm" },
    { key: "Capacitance", value: "Farad" },
    { key: "Magnetic flux", value: "Weber" },
    { key: "Magnetic field strength", value: "Tesla" },
    { key: "Temperature", value: "Kelvin" },
    { key: "Amount of substance", value: "Mole" },
    { key: "Luminous intensity", value: "Candela" },
    { key: "Radioactivity", value: "Becquerel" },
    { key: "Inductance", value: "Henry" },
    { key: "Conductance", value: "Siemens" },
  ],
  "What is the SI unit of %s?",
  "The %s is the SI unit of which physical quantity?",
  "The SI unit of %k is the %v.",
);

/* ------------------------------------------------------------ instruments */

add(
  "gk:instrument",
  "Science and Technology",
  "Moderate",
  [
    { key: "Barometer", value: "Atmospheric pressure" },
    { key: "Hygrometer", value: "Humidity" },
    { key: "Seismograph", value: "Earthquake intensity" },
    { key: "Anemometer", value: "Wind speed" },
    { key: "Lactometer", value: "Purity of milk" },
    { key: "Ammeter", value: "Electric current" },
    { key: "Voltmeter", value: "Potential difference" },
    { key: "Galvanometer", value: "Small electric current" },
    { key: "Odometer", value: "Distance travelled by a vehicle" },
    { key: "Speedometer", value: "Speed of a vehicle" },
    { key: "Altimeter", value: "Altitude" },
    { key: "Sphygmomanometer", value: "Blood pressure" },
    { key: "Spectrometer", value: "Spectrum of light" },
    { key: "Pyrometer", value: "Very high temperature" },
    { key: "Manometer", value: "Pressure of gases" },
    { key: "Salinometer", value: "Salinity of water" },
  ],
  "Which quantity is measured by a %s?",
  "Which instrument is used to measure %s?",
  "A %k measures %v.",
);

/* ---------------------------------------------------------------- sports */

add(
  "gk:sport-players",
  "Sports",
  "Easy",
  [
    { key: "Cricket", value: "11 players" },
    { key: "Football", value: "11 players" },
    { key: "Hockey", value: "11 players" },
    { key: "Volleyball", value: "6 players" },
    { key: "Basketball", value: "5 players" },
    { key: "Kabaddi", value: "7 players" },
    { key: "Water polo", value: "7 players" },
    { key: "Baseball", value: "9 players" },
    { key: "Polo", value: "4 players" },
    { key: "Rugby union", value: "15 players" },
  ],
  "How many players are there in one team in %s?",
  undefined,
  "A %k team has %v on the field.",
);

add(
  "gk:sport-term",
  "Sports",
  "Moderate",
  [
    { key: "Cricket", value: "Googly, LBW, Maiden over" },
    { key: "Football", value: "Dribble, Offside, Penalty kick" },
    { key: "Hockey", value: "Bully, Short corner, Dribble" },
    { key: "Tennis", value: "Deuce, Volley, Love" },
    { key: "Badminton", value: "Smash, Shuttle, Drop shot" },
    { key: "Chess", value: "Checkmate, Gambit, Stalemate" },
    { key: "Boxing", value: "Knockout, Jab, Uppercut" },
    { key: "Golf", value: "Birdie, Bogey, Putt" },
    { key: "Swimming", value: "Butterfly, Freestyle, Breaststroke" },
    { key: "Archery", value: "Bullseye, Quiver, Nock" },
  ],
  "The terms used in which sport are: %s?",
  undefined,
  "The terms %v belong to %k.",
);

/* ---------------------------------------------------------------- awards */

add(
  "gk:award",
  "Static GK",
  "Moderate",
  [
    { key: "Bharat Ratna", value: "Highest civilian award of India" },
    { key: "Param Vir Chakra", value: "Highest wartime military gallantry award of India" },
    { key: "Ashoka Chakra", value: "Highest peacetime gallantry award of India" },
    { key: "Jnanpith Award", value: "Indian literature" },
    { key: "Dronacharya Award", value: "Outstanding sports coaches" },
    { key: "Arjuna Award", value: "Outstanding performance in sports" },
    { key: "Major Dhyan Chand Khel Ratna", value: "Highest sporting honour of India" },
    { key: "Dadasaheb Phalke Award", value: "Lifetime contribution to Indian cinema" },
    { key: "Sahitya Akademi Award", value: "Literary works in Indian languages" },
    { key: "Nobel Peace Prize", value: "Work towards world peace" },
    { key: "Ramon Magsaysay Award", value: "Asia's Nobel for public service" },
    { key: "Borlaug Award", value: "Agricultural research in India" },
  ],
  "The %s is given in which field or for what achievement?",
  undefined,
  "The %k is associated with %v.",
);

/* --------------------------------------------------------------- rivers */

add(
  "gk:river-origin",
  "Indian Geography",
  "Moderate",
  [
    { key: "Ganga", value: "Gangotri glacier, Uttarakhand" },
    { key: "Yamuna", value: "Yamunotri glacier, Uttarakhand" },
    { key: "Narmada", value: "Amarkantak, Madhya Pradesh" },
    { key: "Godavari", value: "Trimbakeshwar, Maharashtra" },
    { key: "Krishna", value: "Mahabaleshwar, Maharashtra" },
    { key: "Kaveri", value: "Talakaveri, Karnataka" },
    { key: "Mahanadi", value: "Sihawa, Chhattisgarh" },
    { key: "Tapti", value: "Betul, Madhya Pradesh" },
    { key: "Sutlej", value: "Rakshastal, Tibet" },
    { key: "Beas", value: "Beas Kund, Himachal Pradesh" },
    { key: "Ravi", value: "Bara Bhangal, Himachal Pradesh" },
    { key: "Chenab", value: "Bara Lacha Pass, Himachal Pradesh" },
    { key: "Jhelum", value: "Verinag, Jammu and Kashmir" },
    { key: "Brahmaputra", value: "Angsi glacier, Tibet" },
    { key: "Indus", value: "Lake Mansarovar, Tibet" },
  ],
  "Where does the river %s originate?",
  undefined,
  "The river %k originates at %v.",
);

/* ------------------------------------------------------------ books */

add(
  "gk:book-author",
  "Static GK",
  "Difficult",
  [
    { key: "Discovery of India", value: "Jawaharlal Nehru" },
    { key: "Gitanjali", value: "Rabindranath Tagore" },
    { key: "Arthashastra", value: "Kautilya (Chanakya)" },
    { key: "Wings of Fire", value: "A. P. J. Abdul Kalam" },
    { key: "My Experiments with Truth", value: "Mahatma Gandhi" },
    { key: "Godan", value: "Munshi Premchand" },
    { key: "Anandamath", value: "Bankim Chandra Chattopadhyay" },
    { key: "Raghuvamsha", value: "Kalidasa" },
    { key: "Panchatantra", value: "Vishnu Sharma" },
    { key: "India Wins Freedom", value: "Maulana Abul Kalam Azad" },
    { key: "The White Tiger", value: "Aravind Adiga" },
    { key: "Train to Pakistan", value: "Khushwant Singh" },
    { key: "Poverty and Un-British Rule in India", value: "Dadabhai Naoroji" },
    { key: "Geetanjali Shree's Tomb of Sand translator", value: "Daisy Rockwell" },
  ],
  "Who is the author of '%s'?",
  undefined,
  "'%k' was written by %v.",
);

/* ------------------------------------------------------ freedom movement */

add(
  "gk:freedom",
  "Indian History",
  "Moderate",
  [
    { key: "Jallianwala Bagh massacre", value: "1919" },
    { key: "Non-Cooperation Movement", value: "1920" },
    { key: "Dandi March or Salt Satyagraha", value: "1930" },
    { key: "Quit India Movement", value: "1942" },
    { key: "First War of Indian Independence", value: "1857" },
    { key: "Formation of the Indian National Congress", value: "1885" },
    { key: "Partition of Bengal", value: "1905" },
    { key: "Champaran Satyagraha", value: "1917" },
    { key: "Simon Commission arrival in India", value: "1928" },
    { key: "Indian independence", value: "1947" },
    { key: "Adoption of the Constitution of India", value: "26 November 1949" },
    { key: "Commencement of the Constitution of India", value: "26 January 1950" },
  ],
  "In which year did the %s take place?",
  undefined,
  "The %k took place in %v.",
);

add(
  "gk:slogan",
  "Indian History",
  "Moderate",
  [
    { key: "Do or Die", value: "Mahatma Gandhi" },
    { key: "Give me blood and I will give you freedom", value: "Subhas Chandra Bose" },
    { key: "Inquilab Zindabad", value: "Bhagat Singh" },
    { key: "Swaraj is my birthright and I shall have it", value: "Bal Gangadhar Tilak" },
    { key: "Jai Jawan Jai Kisan", value: "Lal Bahadur Shastri" },
    { key: "Satyameva Jayate", value: "Madan Mohan Malaviya" },
    { key: "Vande Mataram", value: "Bankim Chandra Chattopadhyay" },
    { key: "Sare Jahan Se Achha", value: "Muhammad Iqbal" },
    { key: "Aaram Haram Hai", value: "Jawaharlal Nehru" },
  ],
  "Who gave the slogan '%s'?",
  undefined,
  "The slogan '%k' is associated with %v.",
);

export const GK_TEMPLATES = templates;
