/**
 * The rest of the General Studies geography, environment, science and
 * economy syllabus.
 *
 * Physical Geography, World Geography, Environment and Ecology, Science and
 * Technology and Indian Economy each carried six or seven chapters, well
 * short of what UPSC, the State PSCs, SSC, the railways, banking, NDA and
 * CAPF set. These are the standard syllabus modules the bank was missing.
 */

import { type Template } from "./core";
import { GK_WIDE, chapterFactory } from "./two-layer";

const templates: Template[] = [];
const pgeo = chapterFactory(templates, "Physical Geography", GK_WIDE);
const wgeo = chapterFactory(templates, "World Geography", GK_WIDE);
const env = chapterFactory(templates, "Environment and Ecology", GK_WIDE);
const st = chapterFactory(templates, "Science and Technology", GK_WIDE);
const eco = chapterFactory(templates, "Indian Economy", GK_WIDE);

/* ===================================================== Physical Geography */

pgeo(
  "pg:rocks-minerals",
  "Rocks, Minerals and the Rock Cycle",
  "In the study of rocks, what is %s?",
  "%k is %v.",
  [
    { key: "Three major types of rock", value: "Igneous, sedimentary and metamorphic" },
    {
      key: "Igneous rock",
      value: "Rock formed by the cooling and solidification of magma or lava",
    },
    { key: "Sedimentary rock", value: "Rock formed by the deposition and compaction of sediments" },
    {
      key: "Metamorphic rock",
      value: "Rock formed when existing rock is altered by heat and pressure",
    },
    { key: "Rock called the parent of all rocks", value: "Igneous rock" },
    { key: "Metamorphic form of limestone", value: "Marble" },
    { key: "Metamorphic form of sandstone", value: "Quartzite" },
    { key: "Metamorphic form of coal", value: "Graphite, and at the highest grade diamond" },
    { key: "Rock type in which fossils are found", value: "Sedimentary rock" },
    { key: "Hardest natural mineral", value: "Diamond" },
  ],
  [
    {
      key: "Intrusive and extrusive igneous rock",
      value:
        "Intrusive cools slowly below the surface with large crystals, extrusive cools quickly on it with fine grain",
    },
    { key: "Batholith", value: "A very large intrusive igneous body exposed after erosion" },
    {
      key: "Mohs scale",
      value: "The scale of mineral hardness from talc at one to diamond at ten",
    },
    {
      key: "Rock cycle",
      value:
        "The continuous transformation of rock from one type to another through melting, weathering and metamorphism",
    },
    {
      key: "Reason the Deccan trap is important",
      value:
        "It is a vast basaltic lava plateau whose weathering gives the fertile black regur soil",
    },
  ],
);

pgeo(
  "pg:earthquakes-volcanoes",
  "Earthquakes, Volcanoes and Plate Tectonics",
  "In tectonic processes, what is %s?",
  "%k is %v.",
  [
    { key: "Focus of an earthquake", value: "The point within the earth where the rupture begins" },
    { key: "Epicentre", value: "The point on the surface directly above the focus" },
    { key: "Instrument that records earthquake waves", value: "The seismograph" },
    { key: "Scale that measures earthquake magnitude", value: "The Richter scale" },
    { key: "Scale that measures earthquake intensity", value: "The Mercalli scale" },
    { key: "Fastest seismic wave", value: "The primary or P wave" },
    { key: "Wave that cannot pass through liquids", value: "The secondary or S wave" },
    { key: "Theory explaining the movement of the crust", value: "Plate tectonics" },
    { key: "Scientist who proposed continental drift", value: "Alfred Wegener" },
    {
      key: "Ring of Fire",
      value: "The belt of volcanoes and earthquakes around the Pacific Ocean",
    },
  ],
  [
    {
      key: "Evidence that the outer core is liquid",
      value: "S waves do not pass through it, creating a shadow zone",
    },
    { key: "Three types of plate boundary", value: "Divergent, convergent and transform" },
    {
      key: "Landform created at a convergent oceanic boundary",
      value: "A deep ocean trench with an island arc",
    },
    {
      key: "Reason the Himalayas are still rising",
      value: "The Indian plate continues to push northward into the Eurasian plate",
    },
    {
      key: "Tsunami",
      value:
        "A series of long waves generated by the sudden displacement of the sea floor, usually by an undersea earthquake",
    },
  ],
);

pgeo(
  "pg:weathering-erosion",
  "Weathering, Erosion and Landform Evolution",
  "In the shaping of landforms, what is %s?",
  "%k is %v.",
  [
    { key: "Weathering", value: "The breakdown of rock in place, without transport" },
    {
      key: "Erosion",
      value: "The wearing away and removal of material by an agent such as water, wind or ice",
    },
    { key: "Chief agent of erosion in humid regions", value: "Running water" },
    { key: "Chief agent of erosion in arid regions", value: "Wind" },
    {
      key: "Landform made by a river in its upper course",
      value: "The V shaped valley, with gorges and waterfalls",
    },
    {
      key: "Landform made by a river in its lower course",
      value: "The flood plain, meander, ox-bow lake and delta",
    },
    { key: "Landform made by a glacier", value: "The U shaped valley, cirque, moraine and fjord" },
    { key: "Wind eroded mushroom shaped rock", value: "The mushroom rock, or gara" },
    {
      key: "Karst topography",
      value: "The landscape formed by the solution of limestone, with caves and sinkholes",
    },
    {
      key: "Stalactite and stalagmite",
      value: "Deposits of calcium carbonate hanging from a cave roof and rising from its floor",
    },
  ],
  [
    {
      key: "Exfoliation",
      value: "The peeling away of rock in curved sheets from repeated heating and cooling",
    },
    {
      key: "Difference between a delta and an estuary",
      value:
        "A delta forms where deposition exceeds removal, an estuary where tides and currents carry sediment away",
    },
    {
      key: "Peneplain",
      value: "An almost level surface produced by prolonged erosion, in Davis's cycle of erosion",
    },
    { key: "Loess", value: "Fine wind-blown silt deposited far from its source, highly fertile" },
    { key: "Yardang", value: "An elongated ridge sculpted by wind abrasion in an arid region" },
  ],
);

pgeo(
  "pg:maps-cartography",
  "Maps, Latitude, Longitude and Time",
  "In map work, what is %s?",
  "%k is %v.",
  [
    { key: "Latitude", value: "The angular distance of a place north or south of the equator" },
    {
      key: "Longitude",
      value: "The angular distance of a place east or west of the prime meridian",
    },
    {
      key: "Prime meridian",
      value: "The zero degree line of longitude, passing through Greenwich",
    },
    {
      key: "Total number of parallels of latitude",
      value: "One hundred and eighty one, including the equator",
    },
    { key: "Total number of meridians of longitude", value: "Three hundred and sixty" },
    { key: "Time difference for each degree of longitude", value: "Four minutes" },
    {
      key: "International Date Line",
      value: "The line near the 180 degree meridian where the date changes",
    },
    { key: "Contour line", value: "A line joining places of equal height above sea level" },
    { key: "Isobar", value: "A line joining places of equal atmospheric pressure" },
    { key: "Isotherm", value: "A line joining places of equal temperature" },
  ],
  [
    {
      key: "Great circle",
      value:
        "Any circle on the globe whose plane passes through the centre of the earth, the shortest route between two points",
    },
    {
      key: "Mercator projection",
      value:
        "A cylindrical projection true in direction and shape but greatly exaggerating area near the poles",
    },
    {
      key: "Reason Indian Standard Time is five and a half hours ahead of GMT",
      value:
        "It is based on 82 degrees 30 minutes east longitude, which is 82.5 times four minutes ahead",
    },
    { key: "Closely spaced contours on a map", value: "They indicate a steep slope" },
    {
      key: "Remote sensing",
      value: "Obtaining information about an object from a distance, usually by satellite sensors",
    },
  ],
);

/* ======================================================== World Geography */

wgeo(
  "wg:world-tribes-cities",
  "World Population, Tribes and Major Cities",
  "In world human geography, what is %s?",
  "%k is %v.",
  [
    { key: "Most populous country of the world", value: "India" },
    { key: "Largest country of the world by area", value: "Russia" },
    { key: "Smallest country of the world", value: "Vatican City" },
    { key: "Tribe of the Kalahari desert", value: "The Bushmen, or San" },
    { key: "Tribe of the Arctic region", value: "The Eskimos, or Inuit" },
    { key: "Nomadic herders of the Sahara", value: "The Bedouin and the Tuareg" },
    {
      key: "Tribe of the Amazon basin",
      value: "The Pygmies of the Congo and the tribes of the Amazon such as the Yanomami",
    },
    { key: "Herders of the Siberian tundra", value: "The Lapps, or Sami, and the Yakut" },
    { key: "Largest city of the world by population", value: "Tokyo" },
    { key: "City on two continents", value: "Istanbul" },
  ],
  [
    { key: "Country called the land of the midnight sun", value: "Norway" },
    { key: "Country called the land of the rising sun", value: "Japan" },
    { key: "Country called the roof of the world", value: "Tibet, in China" },
    { key: "Strait separating Asia from North America", value: "The Bering Strait" },
    { key: "Canal linking the Mediterranean with the Red Sea", value: "The Suez Canal" },
  ],
);

wgeo(
  "wg:world-lakes-straits",
  "World Lakes, Straits, Canals and Islands",
  "Among the water features of the world, what is %s?",
  "%k is %v.",
  [
    { key: "Largest lake of the world", value: "The Caspian Sea" },
    { key: "Deepest lake of the world", value: "Lake Baikal in Russia" },
    { key: "Largest freshwater lake by area", value: "Lake Superior" },
    { key: "Saltiest large water body", value: "The Dead Sea" },
    { key: "Lowest point on the land surface of the earth", value: "The shore of the Dead Sea" },
    { key: "Strait between India and Sri Lanka", value: "The Palk Strait" },
    { key: "Strait at the mouth of the Persian Gulf", value: "The Strait of Hormuz" },
    { key: "Strait between Malaysia and Sumatra", value: "The Strait of Malacca" },
    { key: "Canal linking the Atlantic with the Pacific", value: "The Panama Canal" },
    { key: "Largest island of the world", value: "Greenland" },
  ],
  [
    { key: "Strait between Europe and Africa", value: "The Strait of Gibraltar" },
    {
      key: "Importance of the Strait of Hormuz",
      value: "A very large share of the world's seaborne oil passes through it",
    },
    { key: "Drake Passage", value: "The stretch of sea between South America and Antarctica" },
    {
      key: "Reason the Dead Sea is so saline",
      value: "It has no outlet, so high evaporation concentrates the dissolved salts",
    },
    {
      key: "Great Barrier Reef",
      value: "The world's largest coral reef system, off the coast of Queensland in Australia",
    },
  ],
);

/* ================================================ Environment and Ecology */

env(
  "ev:climate-agreements",
  "Climate Change Agreements and International Bodies",
  "In global environmental governance, what is %s?",
  "%k is %v.",
  [
    {
      key: "Earth Summit of 1992",
      value: "The United Nations Conference on Environment and Development at Rio de Janeiro",
    },
    {
      key: "Convention on climate change adopted at Rio",
      value: "The United Nations Framework Convention on Climate Change",
    },
    { key: "Protocol of 1997 setting binding emission targets", value: "The Kyoto Protocol" },
    { key: "Agreement of 2015 on limiting global warming", value: "The Paris Agreement" },
    {
      key: "Temperature goal of the Paris Agreement",
      value: "Well below two degrees Celsius, with efforts to limit it to 1.5 degrees",
    },
    {
      key: "Nationally Determined Contribution",
      value: "A country's self declared climate action pledge under the Paris Agreement",
    },
    {
      key: "Body that assesses the science of climate change",
      value: "The Intergovernmental Panel on Climate Change",
    },
    { key: "Protocol that protects the ozone layer", value: "The Montreal Protocol of 1987" },
    {
      key: "Convention on biological diversity",
      value:
        "The convention adopted at Rio in 1992 with three objectives including benefit sharing",
    },
    { key: "Convention on wetlands", value: "The Ramsar Convention of 1971" },
  ],
  [
    {
      key: "Common but differentiated responsibilities",
      value:
        "The principle that all states share responsibility but developed countries must lead, given their historical emissions",
    },
    {
      key: "Nagoya Protocol",
      value:
        "The 2010 protocol on access to genetic resources and fair sharing of the benefits from their use",
    },
    {
      key: "Kigali Amendment",
      value: "The 2016 amendment to the Montreal Protocol phasing down hydrofluorocarbons",
    },
    {
      key: "CITES",
      value:
        "The convention regulating international trade in endangered species of wild fauna and flora",
    },
    {
      key: "India's net zero target year",
      value: "2070, announced at the Glasgow climate conference",
    },
  ],
);

env(
  "ev:environmental-laws-india",
  "Indian Environmental Laws and Institutions",
  "In Indian environmental law, what is %s?",
  "%k is %v.",
  [
    { key: "Act protecting wildlife in India", value: "The Wildlife Protection Act, 1972" },
    { key: "Act for the conservation of forests", value: "The Forest Conservation Act, 1980" },
    {
      key: "Umbrella environmental legislation of India",
      value: "The Environment Protection Act, 1986",
    },
    {
      key: "Event that led to the Environment Protection Act",
      value: "The Bhopal gas tragedy of 1984",
    },
    { key: "Act recognising the rights of forest dwellers", value: "The Forest Rights Act, 2006" },
    {
      key: "Tribunal for environmental cases",
      value: "The National Green Tribunal, established in 2010",
    },
    {
      key: "Body that monitors air and water pollution",
      value: "The Central Pollution Control Board",
    },
    {
      key: "Constitutional article on protection of the environment",
      value: "Article 48A, a Directive Principle",
    },
    {
      key: "Fundamental duty relating to the environment",
      value: "Article 51A(g), to protect and improve the natural environment",
    },
    {
      key: "Environmental Impact Assessment",
      value:
        "The study of the likely environmental effects of a proposed project before it is cleared",
    },
  ],
  [
    {
      key: "Schedule of the Wildlife Protection Act with the highest protection",
      value: "Schedule I, which carries the strictest penalties",
    },
    {
      key: "Polluter pays principle",
      value: "The principle that the cost of pollution must be borne by the one who causes it",
    },
    {
      key: "Precautionary principle",
      value:
        "Where there is a threat of serious damage, lack of full scientific certainty is no reason to postpone action",
    },
    {
      key: "Extended producer responsibility",
      value:
        "The obligation on a producer to manage a product through to its disposal, central to the plastic and e-waste rules",
    },
    {
      key: "Coastal Regulation Zone",
      value:
        "The zone along the coast where development is regulated to protect the shoreline and coastal communities",
    },
  ],
);

/* =================================================== Science and Technology */

st(
  "st:space-missions",
  "Indian Space Missions and Launch Vehicles",
  "In the Indian space programme, what is %s?",
  "%k is %v.",
  [
    { key: "Father of the Indian space programme", value: "Dr Vikram Sarabhai" },
    { key: "Year ISRO was founded", value: "1969" },
    { key: "Headquarters of ISRO", value: "Bengaluru" },
    { key: "First Indian satellite", value: "Aryabhata, launched in 1975" },
    { key: "India's first lunar mission", value: "Chandrayaan-1, launched in 2008" },
    { key: "Mission that discovered water molecules on the moon", value: "Chandrayaan-1" },
    { key: "India's Mars mission", value: "Mangalyaan, the Mars Orbiter Mission of 2013" },
    { key: "Mission that landed near the lunar south pole in 2023", value: "Chandrayaan-3" },
    { key: "India's first solar observation mission", value: "Aditya-L1" },
    { key: "India's human spaceflight programme", value: "Gaganyaan" },
  ],
  [
    { key: "Workhorse launch vehicle of ISRO", value: "The Polar Satellite Launch Vehicle" },
    {
      key: "Launch vehicle used for heavy geostationary satellites",
      value: "The GSLV Mark III, now called LVM3",
    },
    {
      key: "Indian regional navigation system",
      value: "NavIC, the Indian Regional Navigation Satellite System",
    },
    {
      key: "Significance of the Mars Orbiter Mission",
      value: "India succeeded at its first attempt and at a remarkably low cost",
    },
    {
      key: "Lagrange point L1",
      value:
        "The point between the earth and the sun where a satellite can observe the sun without eclipse",
    },
  ],
);

st(
  "st:emerging-tech",
  "Artificial Intelligence, Robotics and Emerging Technology",
  "In emerging technology, what is %s?",
  "%k is %v.",
  [
    {
      key: "Artificial intelligence",
      value: "The ability of a machine to perform tasks that normally require human intelligence",
    },
    {
      key: "Machine learning",
      value: "A branch of artificial intelligence in which systems learn patterns from data",
    },
    {
      key: "Internet of Things",
      value: "A network of physical objects with sensors that exchange data over the internet",
    },
    {
      key: "Blockchain",
      value:
        "A distributed ledger in which records are linked cryptographically and are hard to alter",
    },
    {
      key: "Cryptocurrency",
      value: "A digital currency secured by cryptography and recorded on a blockchain",
    },
    {
      key: "Digital currency issued by the Reserve Bank of India",
      value: "The Central Bank Digital Currency, the digital rupee",
    },
    { key: "Big data", value: "Data sets too large and complex for traditional processing tools" },
    {
      key: "Cloud computing",
      value: "Delivery of computing resources as a service over the internet",
    },
    {
      key: "3D printing",
      value: "Additive manufacturing that builds an object layer by layer from a digital model",
    },
    {
      key: "5G technology",
      value: "The fifth generation of mobile networks, giving very high speed and very low latency",
    },
  ],
  [
    {
      key: "Quantum computing",
      value:
        "Computing with qubits that exploit superposition and entanglement to solve certain problems far faster",
    },
    {
      key: "Deep learning",
      value:
        "Machine learning using multi-layered neural networks that learn features directly from raw data",
    },
    {
      key: "Difference between artificial intelligence and machine learning",
      value: "Machine learning is one approach within the wider field of artificial intelligence",
    },
    {
      key: "Digital twin",
      value: "A virtual replica of a physical asset kept in step with it through sensor data",
    },
    {
      key: "Chief risk of generative artificial intelligence",
      value:
        "Convincing but false output, along with bias in the training data and misuse for deception",
    },
  ],
);

/* ============================================================ Indian Economy */

eco(
  "ie:agriculture-industry",
  "Agriculture, Industry and Infrastructure",
  "In the Indian economy, what is %s?",
  "%k is %v.",
  [
    {
      key: "Share of agriculture in India's employment",
      value: "About forty five per cent of the workforce",
    },
    {
      key: "Minimum support price",
      value: "The price announced in advance at which the government will buy a crop",
    },
    {
      key: "Body that recommends the minimum support price",
      value: "The Commission for Agricultural Costs and Prices",
    },
    {
      key: "Green Revolution",
      value:
        "The rise in food grain output from high yielding seeds, fertiliser and assured irrigation",
    },
    {
      key: "White Revolution",
      value: "The rise in milk production, associated with Operation Flood and Verghese Kurien",
    },
    { key: "Blue Revolution", value: "The growth of fisheries and aquaculture" },
    {
      key: "Micro, small and medium enterprises classification basis",
      value: "Investment in plant and machinery together with annual turnover",
    },
    { key: "Index measuring industrial output", value: "The Index of Industrial Production" },
    {
      key: "Body that compiles the Index of Industrial Production",
      value: "The National Statistical Office",
    },
    {
      key: "Public private partnership",
      value: "A long-term contract in which a private party builds or operates a public asset",
    },
  ],
  [
    {
      key: "Disguised unemployment in agriculture",
      value: "More workers on a holding than are needed, so removing some would not reduce output",
    },
    {
      key: "Reason for the low productivity of Indian agriculture",
      value:
        "Small fragmented holdings, dependence on the monsoon, low mechanisation and weak marketing",
    },
    {
      key: "Eight core industries",
      value:
        "Coal, crude oil, natural gas, refinery products, fertilisers, steel, cement and electricity",
    },
    {
      key: "Weight of the core industries in the Index of Industrial Production",
      value: "About forty per cent",
    },
    {
      key: "Production Linked Incentive scheme",
      value:
        "An incentive paid on incremental sales of goods manufactured in India, to build scale in chosen sectors",
    },
  ],
);

eco(
  "ie:financial-markets",
  "Financial Markets, Regulators and Inclusion",
  "In India's financial system, what is %s?",
  "%k is %v.",
  [
    {
      key: "Regulator of the securities market in India",
      value: "The Securities and Exchange Board of India",
    },
    {
      key: "Regulator of the insurance sector",
      value: "The Insurance Regulatory and Development Authority of India",
    },
    {
      key: "Regulator of pensions",
      value: "The Pension Fund Regulatory and Development Authority",
    },
    { key: "Central bank of India", value: "The Reserve Bank of India" },
    { key: "Year the Reserve Bank of India was established", value: "1935" },
    { key: "Year the Reserve Bank of India was nationalised", value: "1949" },
    { key: "Oldest stock exchange of Asia", value: "The Bombay Stock Exchange" },
    { key: "Benchmark index of the National Stock Exchange", value: "The Nifty 50" },
    { key: "Scheme for universal bank accounts", value: "The Pradhan Mantri Jan Dhan Yojana" },
    { key: "Instant payment system of India", value: "The Unified Payments Interface" },
  ],
  [
    {
      key: "Priority sector lending",
      value:
        "The requirement that banks lend a set share of credit to agriculture, small enterprise and weaker sections",
    },
    {
      key: "Non-performing asset",
      value: "A loan on which interest or principal is overdue for more than ninety days",
    },
    {
      key: "Insolvency and Bankruptcy Code",
      value: "The 2016 law giving a time bound process to resolve or liquidate a defaulting firm",
    },
    {
      key: "Small finance bank",
      value:
        "A bank licensed to serve small borrowers, with high priority sector and small ticket lending obligations",
    },
    {
      key: "Financial inclusion",
      value:
        "Access to useful and affordable financial services for all sections, especially the unbanked",
    },
  ],
);

eco(
  "ie:employment-schemes",
  "Employment, Poverty and Government Schemes",
  "Among India's welfare and employment measures, what is %s?",
  "%k is %v.",
  [
    {
      key: "Scheme guaranteeing rural wage employment",
      value: "The Mahatma Gandhi National Rural Employment Guarantee Act scheme",
    },
    {
      key: "Days of employment guaranteed under MGNREGA",
      value: "One hundred days a year to a rural household",
    },
    { key: "Rural housing scheme", value: "The Pradhan Mantri Awas Yojana Gramin" },
    {
      key: "Scheme providing free cooking gas connections",
      value: "The Pradhan Mantri Ujjwala Yojana",
    },
    {
      key: "Health insurance scheme for poor families",
      value: "Ayushman Bharat, the Pradhan Mantri Jan Arogya Yojana",
    },
    {
      key: "Cover provided under Ayushman Bharat",
      value: "Five lakh rupees a family a year for secondary and tertiary care",
    },
    { key: "Food security legislation of India", value: "The National Food Security Act, 2013" },
    { key: "Income support scheme for farmers", value: "The PM Kisan Samman Nidhi" },
    { key: "Skill development mission of India", value: "The Pradhan Mantri Kaushal Vikas Yojana" },
    { key: "Body that replaced the Planning Commission", value: "NITI Aayog, in 2015" },
  ],
  [
    {
      key: "Direct benefit transfer",
      value: "The payment of a subsidy or benefit straight into the beneficiary's bank account",
    },
    {
      key: "JAM trinity",
      value: "Jan Dhan accounts, Aadhaar and mobile, the platform for direct benefit transfer",
    },
    {
      key: "Multidimensional Poverty Index",
      value: "A measure combining deprivation in health, education and standard of living",
    },
    {
      key: "Difference between structural and frictional unemployment",
      value:
        "Structural comes from a mismatch of skills and jobs, frictional from the time taken to move between jobs",
    },
    {
      key: "Periodic Labour Force Survey",
      value:
        "The survey that estimates employment and unemployment in India, conducted by the National Statistical Office",
    },
  ],
);

export const GS_FULL2_TEMPLATES = templates;
