/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyMaterialRouteImport } from './routes/study-material'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TestSeriesRouteImport } from './routes/test-series'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardDoubtsRouteImport } from './routes/dashboard.doubts'
import { Route as DashboardLiveRouteImport } from './routes/dashboard.live'
import { Route as DashboardMaterialsRouteImport } from './routes/dashboard.materials'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardTestsRouteImport } from './routes/dashboard.tests'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as FacultySlugRouteImport } from './routes/faculty.$slug'
import { Route as TestIdRouteImport } from './routes/test.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAiQuestionEngineRouteImport } from './routes/_authenticated/admin.ai-question-engine'
import { Route as AuthenticatedAdminAppBuilderRouteImport } from './routes/_authenticated/admin.app-builder'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminDoubtsRouteImport } from './routes/_authenticated/admin.doubts'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminExamBankRouteImport } from './routes/_authenticated/admin.exam-bank'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated/admin.materials'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminOfflineAccessRouteImport } from './routes/_authenticated/admin.offline-access'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated/admin.storage'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminTestsRouteImport } from './routes/_authenticated/admin.tests'
import { Route as AuthenticatedAdminTextManagerRouteImport } from './routes/_authenticated/admin.text-manager'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminVouchersRouteImport } from './routes/_authenticated/admin.vouchers'
import { Route as TestSeriesLearnSeriesIdRouteImport } from './routes/test-series.learn.$seriesId'
import { Route as TestsLearnTestIdRouteImport } from './routes/tests.learn.$testId'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin.courses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyMaterialRoute = StudyMaterialRouteImport.update({
  id: '/study-material',
  path: '/study-material',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSeriesRoute = TestSeriesRouteImport.update({
  id: '/test-series',
  path: '/test-series',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoubtsRoute = DashboardDoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaterialsRoute = DashboardMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestsRoute = DashboardTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => DashboardRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultySlugRoute = FacultySlugRouteImport.update({
  id: '/faculty/$slug',
  path: '/faculty/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAiQuestionEngineRoute =
  AuthenticatedAdminAiQuestionEngineRouteImport.update({
    id: '/admin/ai-question-engine',
    path: '/admin/ai-question-engine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAppBuilderRoute =
  AuthenticatedAdminAppBuilderRouteImport.update({
    id: '/admin/app-builder',
    path: '/admin/app-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/admin/branding',
    path: '/admin/branding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/admin/content',
    path: '/admin/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/admin/coupons',
    path: '/admin/coupons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDoubtsRoute =
  AuthenticatedAdminDoubtsRouteImport.update({
    id: '/admin/doubts',
    path: '/admin/doubts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/admin/enquiries',
    path: '/admin/enquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExamBankRoute =
  AuthenticatedAdminExamBankRouteImport.update({
    id: '/admin/exam-bank',
    path: '/admin/exam-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/admin/materials',
    path: '/admin/materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOfflineAccessRoute =
  AuthenticatedAdminOfflineAccessRouteImport.update({
    id: '/admin/offline-access',
    path: '/admin/offline-access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/admin/storage',
    path: '/admin/storage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTestsRoute = AuthenticatedAdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTextManagerRoute =
  AuthenticatedAdminTextManagerRouteImport.update({
    id: '/admin/text-manager',
    path: '/admin/text-manager',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVouchersRoute =
  AuthenticatedAdminVouchersRouteImport.update({
    id: '/admin/vouchers',
    path: '/admin/vouchers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TestSeriesLearnSeriesIdRoute = TestSeriesLearnSeriesIdRouteImport.update({
  id: '/learn/$seriesId',
  path: '/learn/$seriesId',
  getParentRoute: () => TestSeriesRoute,
} as any)
const TestsLearnTestIdRoute = TestsLearnTestIdRouteImport.update({
  id: '/tests/learn/$testId',
  path: '/tests/learn/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/admin/courses/$id',
    path: '/admin/courses/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/coins': typeof CoinsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/study-material': typeof StudyMaterialRoute
  '/support': typeof SupportRoute
  '/test-series': typeof TestSeriesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/test/$id': typeof TestIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/admin/ai-question-engine': typeof AuthenticatedAdminAiQuestionEngineRoute
  '/admin/app-builder': typeof AuthenticatedAdminAppBuilderRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/doubts': typeof AuthenticatedAdminDoubtsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/exam-bank': typeof AuthenticatedAdminExamBankRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offline-access': typeof AuthenticatedAdminOfflineAccessRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/admin/text-manager': typeof AuthenticatedAdminTextManagerRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/test-series/learn/$seriesId': typeof TestSeriesLearnSeriesIdRoute
  '/tests/learn/$testId': typeof TestsLearnTestIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/coins': typeof CoinsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/study-material': typeof StudyMaterialRoute
  '/support': typeof SupportRoute
  '/test-series': typeof TestSeriesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/test/$id': typeof TestIdRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/admin/ai-question-engine': typeof AuthenticatedAdminAiQuestionEngineRoute
  '/admin/app-builder': typeof AuthenticatedAdminAppBuilderRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/doubts': typeof AuthenticatedAdminDoubtsRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/exam-bank': typeof AuthenticatedAdminExamBankRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offline-access': typeof AuthenticatedAdminOfflineAccessRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/admin/text-manager': typeof AuthenticatedAdminTextManagerRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/test-series/learn/$seriesId': typeof TestSeriesLearnSeriesIdRoute
  '/tests/learn/$testId': typeof TestsLearnTestIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/classes': typeof ClassesRoute
  '/coins': typeof CoinsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/signup': typeof SignupRoute
  '/study-material': typeof StudyMaterialRoute
  '/support': typeof SupportRoute
  '/test-series': typeof TestSeriesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tests': typeof DashboardTestsRoute
  '/faculty/$slug': typeof FacultySlugRoute
  '/test/$id': typeof TestIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/_authenticated/admin/ai-question-engine': typeof AuthenticatedAdminAiQuestionEngineRoute
  '/_authenticated/admin/app-builder': typeof AuthenticatedAdminAppBuilderRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/doubts': typeof AuthenticatedAdminDoubtsRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/exam-bank': typeof AuthenticatedAdminExamBankRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/offline-access': typeof AuthenticatedAdminOfflineAccessRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/_authenticated/admin/text-manager': typeof AuthenticatedAdminTextManagerRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vouchers': typeof AuthenticatedAdminVouchersRoute
  '/test-series/learn/$seriesId': typeof TestSeriesLearnSeriesIdRoute
  '/tests/learn/$testId': typeof TestsLearnTestIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/classes'
    | '/coins'
    | '/dashboard'
    | '/downloads'
    | '/forgot-password'
    | '/games'
    | '/learn'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/study-material'
    | '/support'
    | '/test-series'
    | '/auth/callback'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/doubts'
    | '/dashboard/live'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/student'
    | '/dashboard/tests'
    | '/faculty/$slug'
    | '/test/$id'
    | '/courses/'
    | '/dashboard/'
    | '/faculty/'
    | '/admin/ai-question-engine'
    | '/admin/app-builder'
    | '/admin/branding'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/doubts'
    | '/admin/enquiries'
    | '/admin/exam-bank'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/offline-access'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/students'
    | '/admin/tests'
    | '/admin/text-manager'
    | '/admin/users'
    | '/admin/vouchers'
    | '/test-series/learn/$seriesId'
    | '/tests/learn/$testId'
    | '/admin/'
    | '/admin/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/classes'
    | '/coins'
    | '/downloads'
    | '/forgot-password'
    | '/games'
    | '/learn'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/study-material'
    | '/support'
    | '/test-series'
    | '/auth/callback'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/doubts'
    | '/dashboard/live'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/student'
    | '/dashboard/tests'
    | '/faculty/$slug'
    | '/test/$id'
    | '/courses'
    | '/dashboard'
    | '/faculty'
    | '/admin/ai-question-engine'
    | '/admin/app-builder'
    | '/admin/branding'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/doubts'
    | '/admin/enquiries'
    | '/admin/exam-bank'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/offline-access'
    | '/admin/payments'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/students'
    | '/admin/tests'
    | '/admin/text-manager'
    | '/admin/users'
    | '/admin/vouchers'
    | '/test-series/learn/$seriesId'
    | '/tests/learn/$testId'
    | '/admin'
    | '/admin/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/classes'
    | '/coins'
    | '/dashboard'
    | '/downloads'
    | '/forgot-password'
    | '/games'
    | '/learn'
    | '/login'
    | '/quiz'
    | '/reset-password'
    | '/results'
    | '/signup'
    | '/study-material'
    | '/support'
    | '/test-series'
    | '/auth/callback'
    | '/courses/$slug'
    | '/dashboard/courses'
    | '/dashboard/doubts'
    | '/dashboard/live'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/student'
    | '/dashboard/tests'
    | '/faculty/$slug'
    | '/test/$id'
    | '/courses/'
    | '/dashboard/'
    | '/faculty/'
    | '/_authenticated/admin/ai-question-engine'
    | '/_authenticated/admin/app-builder'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/doubts'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/exam-bank'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/offline-access'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/tests'
    | '/_authenticated/admin/text-manager'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vouchers'
    | '/test-series/learn/$seriesId'
    | '/tests/learn/$testId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ClassesRoute: typeof ClassesRoute
  CoinsRoute: typeof CoinsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamesRoute: typeof GamesRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  SignupRoute: typeof SignupRoute
  StudyMaterialRoute: typeof StudyMaterialRoute
  SupportRoute: typeof SupportRoute
  TestSeriesRoute: typeof TestSeriesRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  FacultySlugRoute: typeof FacultySlugRoute
  TestIdRoute: typeof TestIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  TestsLearnTestIdRoute: typeof TestsLearnTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-material': {
      id: '/study-material'
      path: '/study-material'
      fullPath: '/study-material'
      preLoaderRoute: typeof StudyMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-series': {
      id: '/test-series'
      path: '/test-series'
      fullPath: '/test-series'
      preLoaderRoute: typeof TestSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doubts': {
      id: '/dashboard/doubts'
      path: '/doubts'
      fullPath: '/dashboard/doubts'
      preLoaderRoute: typeof DashboardDoubtsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/materials': {
      id: '/dashboard/materials'
      path: '/materials'
      fullPath: '/dashboard/materials'
      preLoaderRoute: typeof DashboardMaterialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests': {
      id: '/dashboard/tests'
      path: '/tests'
      fullPath: '/dashboard/tests'
      preLoaderRoute: typeof DashboardTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/$slug': {
      id: '/faculty/$slug'
      path: '/faculty/$slug'
      fullPath: '/faculty/$slug'
      preLoaderRoute: typeof FacultySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-question-engine': {
      id: '/_authenticated/admin/ai-question-engine'
      path: '/admin/ai-question-engine'
      fullPath: '/admin/ai-question-engine'
      preLoaderRoute: typeof AuthenticatedAdminAiQuestionEngineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/app-builder': {
      id: '/_authenticated/admin/app-builder'
      path: '/admin/app-builder'
      fullPath: '/admin/app-builder'
      preLoaderRoute: typeof AuthenticatedAdminAppBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/doubts': {
      id: '/_authenticated/admin/doubts'
      path: '/admin/doubts'
      fullPath: '/admin/doubts'
      preLoaderRoute: typeof AuthenticatedAdminDoubtsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/exam-bank': {
      id: '/_authenticated/admin/exam-bank'
      path: '/admin/exam-bank'
      fullPath: '/admin/exam-bank'
      preLoaderRoute: typeof AuthenticatedAdminExamBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/admin/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/offline-access': {
      id: '/_authenticated/admin/offline-access'
      path: '/admin/offline-access'
      fullPath: '/admin/offline-access'
      preLoaderRoute: typeof AuthenticatedAdminOfflineAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/admin/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tests': {
      id: '/_authenticated/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AuthenticatedAdminTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/text-manager': {
      id: '/_authenticated/admin/text-manager'
      path: '/admin/text-manager'
      fullPath: '/admin/text-manager'
      preLoaderRoute: typeof AuthenticatedAdminTextManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vouchers': {
      id: '/_authenticated/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AuthenticatedAdminVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/test-series/learn/$seriesId': {
      id: '/test-series/learn/$seriesId'
      path: '/learn/$seriesId'
      fullPath: '/test-series/learn/$seriesId'
      preLoaderRoute: typeof TestSeriesLearnSeriesIdRouteImport
      parentRoute: typeof TestSeriesRoute
    }
    '/tests/learn/$testId': {
      id: '/tests/learn/$testId'
      path: '/tests/learn/$testId'
      fullPath: '/tests/learn/$testId'
      preLoaderRoute: typeof TestsLearnTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/admin/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAiQuestionEngineRoute: typeof AuthenticatedAdminAiQuestionEngineRoute
  AuthenticatedAdminAppBuilderRoute: typeof AuthenticatedAdminAppBuilderRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminDoubtsRoute: typeof AuthenticatedAdminDoubtsRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminExamBankRoute: typeof AuthenticatedAdminExamBankRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOfflineAccessRoute: typeof AuthenticatedAdminOfflineAccessRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTestsRoute: typeof AuthenticatedAdminTestsRoute
  AuthenticatedAdminTextManagerRoute: typeof AuthenticatedAdminTextManagerRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVouchersRoute: typeof AuthenticatedAdminVouchersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAiQuestionEngineRoute:
    AuthenticatedAdminAiQuestionEngineRoute,
  AuthenticatedAdminAppBuilderRoute: AuthenticatedAdminAppBuilderRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminDoubtsRoute: AuthenticatedAdminDoubtsRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminExamBankRoute: AuthenticatedAdminExamBankRoute,
  AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOfflineAccessRoute: AuthenticatedAdminOfflineAccessRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTestsRoute: AuthenticatedAdminTestsRoute,
  AuthenticatedAdminTextManagerRoute: AuthenticatedAdminTextManagerRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVouchersRoute: AuthenticatedAdminVouchersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCoursesIdRoute: AuthenticatedAdminCoursesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardDoubtsRoute: typeof DashboardDoubtsRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMaterialsRoute: typeof DashboardMaterialsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTestsRoute: typeof DashboardTestsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardDoubtsRoute: DashboardDoubtsRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMaterialsRoute: DashboardMaterialsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTestsRoute: DashboardTestsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TestSeriesRouteChildren {
  TestSeriesLearnSeriesIdRoute: typeof TestSeriesLearnSeriesIdRoute
}

const TestSeriesRouteChildren: TestSeriesRouteChildren = {
  TestSeriesLearnSeriesIdRoute: TestSeriesLearnSeriesIdRoute,
}

const TestSeriesRouteWithChildren = TestSeriesRoute._addFileChildren(
  TestSeriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ClassesRoute: ClassesRoute,
  CoinsRoute: CoinsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamesRoute: GamesRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  SignupRoute: SignupRoute,
  StudyMaterialRoute: StudyMaterialRoute,
  SupportRoute: SupportRoute,
  TestSeriesRoute: TestSeriesRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  FacultySlugRoute: FacultySlugRoute,
  TestIdRoute: TestIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  TestsLearnTestIdRoute: TestsLearnTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
